[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token 2022 Integration Tests"
edition = "2018"
license = "Apache-2.0"
name = "spl-token-2022-test"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.0.1"

[features]
test-bpf = []

[dev-dependencies]
async-trait = "0.1"
solana-program-test = "=1.9.5"
solana-sdk = "=1.9.5"
spl-associated-token-account = { version = "1.0.5", path = "../../associated-token-account/program" }
spl-token-2022 = { version = "0.2", path="../program-2022", features = ["no-entrypoint"] }
spl-token-client = { version = "0.0.1", path = "../client" }
