[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token 2022 Integration Tests"
edition = "2021"
license = "Apache-2.0"
name = "spl-token-2022-test"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.0.1"

[features]
test-sbf = ["zk-ops"]
default = ["zk-ops"]
zk-ops = []

[build-dependencies]
walkdir = "2"

[dev-dependencies]
async-trait = "0.1"
borsh = "1.5.3"
bytemuck = "1.20.0"
futures-util = "0.3"
solana-program = "2.1.0"
solana-program-test = "2.1.0"
solana-sdk = "2.1.0"
spl-associated-token-account = { version = "6.0.0", path = "../../associated-token-account/program" }
spl-elgamal-registry = { version = "0.1.0", path = "../confidential-transfer/elgamal-registry" }
spl-memo = { version = "6.0.0", features = ["no-entrypoint"] }
spl-pod = { version = "0.5.0", path = "../../libraries/pod" }
spl-record = { version = "0.3.0", path = "../../record/program", features = [
    "no-entrypoint",
]}
spl-token-2022 = { version = "6.0.0", path = "../program-2022", features = [
  "no-entrypoint",
] }
spl-token-confidential-transfer-proof-extraction = { version = "0.2.0", path = "../confidential-transfer/proof-extraction" }
spl-token-confidential-transfer-proof-generation = { version = "0.2.0", path = "../confidential-transfer/proof-generation" }
spl-instruction-padding = { version = "0.3.0", path = "../../instruction-padding/program", features = [
  "no-entrypoint",
] }
spl-tlv-account-resolution = { version = "0.9.0", path = "../../libraries/tlv-account-resolution" }
spl-token-client = { version = "0.13.0", path = "../client" }
spl-token-group-interface = { version = "0.5.0", path = "../../token-group/interface" }
spl-token-metadata-interface = { version = "0.6.0", path = "../../token-metadata/interface" }
spl-transfer-hook-example = { version = "0.6", path = "../transfer-hook/example", features = [
  "no-entrypoint",
] }
spl-transfer-hook-interface = { version = "0.9.0", path = "../transfer-hook/interface" }
test-case = "3.3"
