[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token 2022 Integration Tests"
edition = "2021"
license = "Apache-2.0"
name = "spl-token-2022-test"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.0.1"

[features]
test-sbf = ["zk-ops"]
default = ["zk-ops"]
zk-ops = []
proof-program = ["spl-token-2022/proof-program"]

[build-dependencies]
walkdir = "2"

[dev-dependencies]
async-trait = "0.1"
solana-program = "=1.14.12"
solana-program-test = "=1.14.12"
solana-sdk = "=1.14.12"
spl-associated-token-account = { version = "1.1", path = "../../associated-token-account/program" }
spl-memo = { version = "3.0.1", path = "../../memo/program", features = ["no-entrypoint"] }
spl-token-2022 = { version = "0.6", path="../program-2022", features = ["no-entrypoint"] }
spl-instruction-padding = { version = "0.1.0", path="../../instruction-padding/program", features = ["no-entrypoint"] }
spl-token-client = { version = "0.5", path = "../client" }
spl-transfer-hook-example = { version = "0.1", path="../transfer-hook-example", features = ["no-entrypoint"] }
spl-transfer-hook-interface = { version = "0.1", path="../transfer-hook-interface" }
