[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token Rust Client"
edition = "2018"
license = "Apache-2.0"
name = "spl-token-client"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.0.1"

[dependencies]
async-trait = "0.1"
solana-client = "=1.9.2"
solana-program-test = "=1.9.2"
solana-sdk = "=1.9.2"
spl-associated-token-account = { version = "1.0", features = ["no-entrypoint"] }
spl-token = { version = "3.2", path="../program", features = [ "no-entrypoint" ] }
thiserror = "1.0"
