[package]
name = "spl-token-collection"
version = "0.1.0"
description = "Solana Program Library Token Collection"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
solana-program = ">=1.18.11,<=2"
spl-pod = { version = "0.2.2", path = "../../libraries/pod" }
spl-program-error = { version = "0.4.0" , path = "../../libraries/program-error" }
spl-token-2022 = { version = "3.0.2", path = "../../token/program-2022", features = ["no-entrypoint"] }
spl-token-group-example = { version = "0.2", path = "../../token-group/example", features = ["no-entrypoint"] }
spl-token-group-interface = { version = "0.2.3", path = "../../token-group/interface" }
spl-token-metadata-interface = { version = "0.3.3", path = "../../token-metadata/interface" }
spl-type-length-value = { version = "0.4.3", path = "../../libraries/type-length-value" }

[dev-dependencies]
solana-program-test = ">=1.18.11,<=2"
solana-sdk = ">=1.18.11,<=2"
spl-discriminator = { version = "0.2.2", path = "../../libraries/discriminator" }
spl-token-client = { version = "0.10.0", path = "../../token/client" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
