[package]
name = "spl-transfer-hook-example"
version = "0.6.0"
description = "Solana Program Library Transfer Hook Example Program"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
default = ["forbid-additional-mints"]
no-entrypoint = []
test-sbf = []
forbid-additional-mints = []

[dependencies]
arrayref = "0.3.7"
solana-program = ">=1.18.11,<=2"
spl-tlv-account-resolution = { version = "0.6.3" , path = "../../../libraries/tlv-account-resolution" }
spl-token-2022 = { version = "3.0.2",  path = "../../program-2022", features = ["no-entrypoint"] }
spl-transfer-hook-interface = { version = "0.6.3" , path = "../interface" }
spl-type-length-value = { version = "0.4.3" , path = "../../../libraries/type-length-value" }

[dev-dependencies]
solana-program-test = ">=1.18.11,<=2"
solana-sdk = ">=1.18.11,<=2"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
