[package]
name = "test-client"
version = "0.1.0"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
publish = false
edition = "2018"

# Used to ensure that SPL programs are buildable by external clients

[dependencies]
solana-sdk = "1.3.12"
spl-memo = { path = "../../memo/program" }
spl-token = { path = "../../token/program" }
spl-token-v3 = { path = "../../token/program-v3" }
spl-token-swap = { path = "../../token-swap/program" }
