[package]
name = "test-client"
version = "0.1.0"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
publish = false
edition = "2021"

# Used to ensure that SPL programs are buildable by external clients

[dependencies]
solana-sdk = "2.1.0"
spl-memo = { version = "6.0.0", features = [ "no-entrypoint" ] }
spl-token = { path = "../../token/program", features = [ "no-entrypoint" ] }
spl-token-swap = { path = "../../token-swap/program", features = [ "no-entrypoint" ] }
