[package]
name = "spl-discriminator-syn"
version = "0.2.0"
description = "Token parsing and generating library for the `spl-discriminator` library"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
sha2 = "0.10"
syn = { version = "2.0", features = ["full"] }
thiserror = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
