[package]
name = "spl-token-lending"
version = "0.2.0"
description = "Solana Program Library Token Lending"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.8"
bytemuck = "1.18.0"
num-derive = "0.4"
num-traits = "0.2"
solana-program = "2.0.3"
spl-token = { version = "6.0", path = "../../token/program", features = [ "no-entrypoint" ] }
thiserror = "1.0"
uint = "0.9"

[dev-dependencies]
assert_matches = "1.5.0"
proptest = "1.5"
solana-program-test = "2.0.3"
solana-sdk = "2.0.3"

[lib]
crate-type = ["cdylib", "lib"]
