[package]
name = "solend-program"
version = "0.1.0"
description = "Solend Program"
authors = ["Solend Maintainers <maintainers@solend.fi>"]
repository = "https://github.com/solendprotocol/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
pyth-sdk-solana = "0.7.0"
solana-program = "=1.14.10"
spl-token = { version = "3.3.0", features=["no-entrypoint"] }
solend-sdk = { path = "../sdk" }
static_assertions = "1.1.0"
switchboard-program = "0.2.0"
switchboard-v2 = "0.1.3"

[dev-dependencies]
assert_matches = "1.5.0"
bytemuck = "1.5.1"
base64 = "0.13"
log = "0.4.14"
proptest = "1.0"
solana-program-test = "=1.14.10"
solana-sdk = "=1.14.10"
serde = "=1.0.140"
serde_yaml = "0.8"
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
