[package]
name = "spl-token-group-interface"
version = "0.2.3"
description = "Solana Program Library Token Group Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = "1.15.0"
solana-program = ">=1.18.2,<=2"
spl-discriminator = { version = "0.2.2" , path = "../../libraries/discriminator" }
spl-pod = { version = "0.2.2" , path = "../../libraries/pod", features = ["borsh"] }
spl-program-error = { version = "0.4.0" , path = "../../libraries/program-error" }

[dev-dependencies]
spl-type-length-value = { version = "0.4.3", path = "../../libraries/type-length-value", features = ["derive"] }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
