version: 2
updates:
- package-ecosystem: npm
  directory: "/token/js"
  schedule:
    interval: daily
    time: "01:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 3
  labels:
    - "automerge"
- package-ecosystem: npm
  directory: "/token-swap/js"
  schedule:
    interval: daily
    time: "01:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 3
  labels:
    - "automerge"
- package-ecosystem: cargo
  directory: "/token"
  schedule:
    interval: daily
    time: "01:00"
    timezone: America/Los_Angeles
  labels:
    - "automerge"
  open-pull-requests-limit: 3
- package-ecosystem: cargo
  directory: "/memo"
  schedule:
    interval: daily
    time: "01:00"
    timezone: America/Los_Angeles
  labels:
    - "automerge"
  open-pull-requests-limit: 3
- package-ecosystem: cargo
  directory: "/token-swap"
  schedule:
    interval: daily
    time: "01:00"
    timezone: America/Los_Angeles
  labels:
    - "automerge"
  open-pull-requests-limit: 3
- package-ecosystem: cargo
  directory: "/ci/client"
  schedule:
    interval: daily
    time: "01:00"
    timezone: America/Los_Angeles
  labels:
    - "automerge"
  open-pull-requests-limit: 3 
  
