[package]
name = "spl-governance-test-sdk"
version = "0.1.3"
description = "Solana Program Library Governance Program Test SDK"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = "0.3.7"
bincode = "1.3.2"
borsh = "0.10"
lazy_static = "1.4.0"
num-derive = "0.4"
num-traits = "0.2"
serde = "1.0.193"
serde_derive = "1.0.103"
solana-program = "1.17.2"
solana-program-test = "1.17.2"
solana-sdk = "1.17.2"
spl-token = { version = "4.0", path = "../../token/program", features = [ "no-entrypoint" ] }
thiserror = "1.0"
