dist: bionic
sudo: required

notifications:
  email: false

cache:
  cargo: true
  directories:
    - "~/.npm"

services:
  - docker

jobs:
  include:
    - name: "Test programs as clients"
      language: rust
      install:
        source .travis/install-program-deps.sh
      script:
        ./ci/clients.sh

    - name: "Test Memo"
      language: rust
      install:
        source .travis/install-program-deps.sh
      script:
        ./ci/memo.sh

    - name: "Test Token"
      language: rust
      install:
        source .travis/install-program-deps.sh
      script:
        ./ci/token.sh

    - name: "Test Token-Swap"
      language: rust
      install:
        source .travis/install-program-deps.sh
      script:
        ./ci/token-swap.sh

    # docs pull request or commit to master
    - name: "Build Docs"
      if: type IN (push, pull_request) AND branch = master
      language: node_js
      node_js:
        - "node"

      before_install:
        - .travis/affects.sh docs/ .travis || travis_terminate 0
        - cd docs/
        - source .travis/before_install.sh
      script:
        - source .travis/script.sh
