dist: bionic
sudo: required

notifications:
  email: false

cache:
  cargo: true
  directories:
    - "~/.npm"
    - "~/.cache"

services:
  - docker

env:
  global:
    - RUST_BACKTRACE=1

jobs:
  include:
    - name: "Build programs"
      language: rust
      install:
        source .travis/install-program-deps.sh
      script:
        - ci/script.sh

    # docs pull request or commit to master
    - name: "Build Docs"
      if: type IN (push, pull_request) AND branch = master
      language: node_js
      node_js:
        - "node"

      before_install:
        - .travis/affects.sh docs/ .travis || travis_terminate 0
        - cd docs/
        - source .travis/before_install.sh
      script:
        - source .travis/script.sh
