[package]
name = "spl-token-v3"
version = "3.0.0"
description = "Solana Program Library Token v3"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []

[dependencies]
arrayref = "0.3.6"
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.1"
solana-program = "1.4.6"
thiserror = "1.0"

[dev-dependencies]
solana-sdk = "1.4.5"

[lib]
crate-type = ["cdylib", "lib"]
