[package]
name = "spl-single-pool-cli"
version = "1.0.0"
description = "Solana Program Library Single-Validator Stake Pool Command-line Utility"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
tokio = "1.14"
clap = { version = "3.2.23", features = ["derive"] }
console = "0.15.7"
borsh = "0.10"
bincode = "1.3.1"
serde = "1.0.188"
serde_derive = "1.0.103"
serde_json = "1.0.105"
serde_with = "3.3.0"
solana-account-decoder = "=1.16.3"
solana-clap-v3-utils = "=1.16.3"
solana-cli-config = "=1.16.3"
solana-cli-output = "=1.16.3"
solana-client = "=1.16.3"
solana-logger = "=1.16.3"
solana-remote-wallet = "=1.16.3"
solana-sdk = "=1.16.3"
solana-transaction-status = "=1.16.3"
solana-vote-program = "=1.16.3"
spl-token = { version = "4.0", path="../../token/program", features = [ "no-entrypoint" ] }
spl-token-client = { version = "0.6", path="../../token/client" }
spl-associated-token-account = { version = "2.0", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
spl-single-validator-pool = { version = "1.0.0", path="../program", features = [ "no-entrypoint" ] }

[dev-dependencies]
solana-test-validator = "=1.16.3"
serial_test = "2.0.0"
test-case = "3.1"
tempfile = "3.8.0"

[[bin]]
name = "spl-single-pool"
path = "src/main.rs"
