[package]
name = "spl-single-pool-cli"
version = "1.0.0"
description = "Solana Program Library Single-Validator Stake Pool Command-line Utility"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
tokio = "1.39"
clap = { version = "3.2.23", features = ["derive"] }
console = "0.15.8"
borsh = "1.5.1"
bincode = "1.3.1"
serde = "1.0.209"
serde_derive = "1.0.103"
serde_json = "1.0.125"
serde_with = "3.9.0"
solana-account-decoder = "2.0.3"
solana-clap-v3-utils = "2.0.3"
solana-cli-config = "2.0.3"
solana-cli-output = "2.0.3"
solana-client = "2.0.3"
solana-logger = "2.0.3"
solana-remote-wallet = "2.0.3"
solana-sdk = "2.0.3"
solana-transaction-status = "2.0.3"
solana-vote-program = "2.0.3"
spl-token = { version = "6.0", path = "../../token/program", features = [
  "no-entrypoint",
] }
spl-token-client = { version = "0.11.0", path = "../../token/client" }
spl-associated-token-account = { version = "4.0.0", path = "../../associated-token-account/program", features = [
  "no-entrypoint",
] }
spl-single-pool = { version = "1.0.0", path = "../program", features = [
  "no-entrypoint",
] }

[dev-dependencies]
solana-test-validator = "2.0.3"
serial_test = "3.1.1"
test-case = "3.3"
tempfile = "3.12.0"

[[bin]]
name = "spl-single-pool"
path = "src/main.rs"
