[package]
name = "spl-single-pool-cli"
version = "1.0.0"
description = "Solana Program Library Single-Validator Stake Pool Command-line Utility"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
tokio = "1.38"
clap = { version = "3.2.23", features = ["derive"] }
console = "0.15.8"
borsh = "1.5.1"
bincode = "1.3.1"
serde = "1.0.203"
serde_derive = "1.0.103"
serde_json = "1.0.117"
serde_with = "3.8.1"
solana-account-decoder = ">=1.18.11,<=2"
solana-clap-v3-utils = ">=1.18.11,<=2"
solana-cli-config = ">=1.18.11,<=2"
solana-cli-output = ">=1.18.11,<=2"
solana-client = ">=1.18.11,<=2"
solana-logger = ">=1.18.11,<=2"
solana-remote-wallet = ">=1.18.11,<=2"
solana-sdk = ">=1.18.11,<=2"
solana-transaction-status = ">=1.18.11,<=2"
solana-vote-program = ">=1.18.11,<=2"
spl-token = { version = "4.0", path = "../../token/program", features = [
  "no-entrypoint",
] }
spl-token-client = { version = "0.10.0", path = "../../token/client" }
spl-associated-token-account = { version = "3.0.2", path = "../../associated-token-account/program", features = [
  "no-entrypoint",
] }
spl-single-pool = { version = "1.0.0", path = "../program", features = [
  "no-entrypoint",
] }

[dev-dependencies]
solana-test-validator = ">=1.18.11,<=2"
serial_test = "3.1.1"
test-case = "3.3"
tempfile = "3.10.1"

[[bin]]
name = "spl-single-pool"
path = "src/main.rs"
