[package]
name = "spl-governance-addin-api"
version = "0.1.3"
description = "Solana Program Library Governance Addin Api"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
borsh = "1.3"
spl-governance-tools= { version = "0.1.3", path ="../tools"}
solana-program = "1.17.6"
