[package]
name = "spl-token-confidential-transfer-ciphertext-arithmetic"
version = "0.2.0"
description = "Solana Program Library Confidential Transfer Ciphertext Arithmetic"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bytemuck = "1.20.0"
solana-curve25519 = "2.1.0"
solana-zk-sdk = "2.1.0"

[dev-dependencies]
spl-token-confidential-transfer-proof-generation = { version = "0.2.0", path = "../proof-generation" }
curve25519-dalek = "4.1.3"

[lib]
crate-type = ["cdylib", "lib"]
