
[package]
name = "spl-themis-client"
version = "0.1.0"
description = "SPL THEMIS client"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
skip-no-mangle = ["solana-sdk/skip-no-mangle"]
program = ["solana-sdk/program"]
default = ["solana-sdk/default"]

[dependencies]

[dev-dependencies]
borsh = "0.7.1"
curve25519-dalek = { version = "2", default-features = false, features = ["serde", "borsh"], git = "https://github.com/garious/curve25519-dalek", rev = "60efef3553d6bf3d7f3b09b5f97acd54d72529ff" }
elgamal_ristretto = { git = "https://github.com/garious/elgamal", rev = "b0a2f5b2cbba052096aed56c26e3047c03fdbe70" }
solana-banks-client = "1.3.13"
solana-banks-server = "1.3.13"
solana-bpf-loader-program = "1.3.13"
solana_rbpf = "=0.1.31"
solana-runtime = "1.3.13"
solana-sdk = "1.3.13"
spl-themis = { version = "0.1.0", path = "../program" }
tokio = "0.2"

[lib]
crate-type = ["cdylib", "lib"]
