[package]
name = "spl-themis-ristretto"
version = "0.1.0"
description = "Solana Program Library THEMIS"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
default = ["elgamal_ristretto/program"]

[dependencies]
bincode = "1.3"
borsh = "0.7.1"
curve25519-dalek = { git = "https://github.com/garious/curve25519-dalek", rev = "60efef3553d6bf3d7f3b09b5f97acd54d72529ff", features = ["borsh"] }
elgamal_ristretto = { git = "https://github.com/garious/elgamal", rev = "db1eef8e01b8a6e93d3bdc64ab2c1acb39cb64d6", default-features = false }
getrandom = { version = "0.1.15", features = ["dummy"] }
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8.1"
solana-program = "1.5.1"
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]
