
# Note: This crate must be built using do.sh

[package]
name = "spl-themis-ristretto"
version = "0.1.0"
description = "Solana Program Library THEMIS"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
skip-no-mangle = ["solana-sdk/skip-no-mangle"]
program = ["solana-sdk/program"]
default = ["solana-sdk/default"]

[dependencies]
bincode = "1.3"
borsh = "0.7.1"
curve25519-dalek = { git = "https://github.com/garious/curve25519-dalek", rev = "60efef3553d6bf3d7f3b09b5f97acd54d72529ff", features = ["borsh"] }
elgamal_ristretto = { git = "https://github.com/garious/elgamal", rev = "260763fb67c34debe3915b39d95b6e7b3e1461d0" }
getrandom = { version = "0.1.15", features = ["dummy"] }
num-derive = "0.3"
num-traits = "0.2"
rand = "0.7.0"
solana-sdk = { version = "1.3.14", default-features = false, optional = true }
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]

