[package]
name = "spl-token-swap"
version = "0.1.0"
description = "Solana Program Library Token Swap"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
exclude_entrypoint = []
production = []

[dependencies]
arrayref = "0.3.6"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "1.4.3"
spl-token = { path = "../../token/program", features = [ "exclude_entrypoint" ] }
thiserror = "1.0"

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]
