[package]
name = "spl-token-swap"
version = "3.0.0"
description = "Solana Program Library Token Swap"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
production = []
fuzz = ["arbitrary", "roots"]

[dependencies]
arrayref = "0.3.9"
enum_dispatch = "0.3.13"
num-derive = "0.4"
num-traits = "0.2"
solana-program = "2.1.0"
spl-math = { version = "0.3", path = "../../libraries/math" }
spl-token = { version = "7.0", path = "../../token/program", features = [ "no-entrypoint" ] }
spl-token-2022 = { version = "6.0.0", path = "../../token/program-2022", features = [ "no-entrypoint" ] }
thiserror = "2.0"
arbitrary = { version = "1.4", features = ["derive"], optional = true }
roots = { version = "0.0.8", optional = true }

[dev-dependencies]
proptest = "1.5"
roots = "0.0.8"
solana-sdk = "2.1.0"
test-case = "3.3"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
