
# Note: This crate must be built using do.sh

[package]
name = "spl-token-swap"
version = "0.1.0"
description = "Solana Program Library Token Swap"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
skip-no-mangle = ["solana-sdk/skip-no-mangle"]
program = ["solana-sdk/program", "spl-token/program", "spl-token/no-entrypoint"]
default = ["solana-sdk/default", "spl-token/default"]

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
remove_dir_all = "=0.5.0"
solana-sdk = { version = "1.3.7", default-features = false, optional = true }
spl-token = { path = "../../token/program", default-features = false, optional = true }
thiserror = "1.0"

[dev-dependencies]
rand = { version = "0.7.0"}

[lib]
name = "spl_token_swap"
crate-type = ["cdylib", "lib"]
