[package]
name = "solana-program-template"
version = "0.1.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.1"
solana-program = "1.6.6"
thiserror = "1.0"
borsh = "0.8.2"
heap-storage = { path="../program/", features = [ "no-entrypoint" ] }

[dev-dependencies]
solana-program-test = "1.6.6"
solana-sdk = "1.6.6"

[lib]
crate-type = ["cdylib", "lib"]

[workspace]