[package]
name = "spl-memo"
version = "1.0.9"
description = "Solana Program Library Memo"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
exclude_entrypoint = []

[dependencies]
solana-program = "1.4.4"

[lib]
crate-type = ["cdylib", "lib"]
