[package]
name = "spl-token"
version = "6.0.0"
description = "Solana Program Library Token"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.8"
bytemuck = "1.18.0"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.3"
solana-program = "2.0.3"
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.5.0"
proptest = "1.5"
serial_test = "3.1.1"
solana-program-test = "2.0.3"
solana-sdk = "2.0.3"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
