[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token Command-line Utility"
edition = "2018"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "spl-token-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "2.0.6"

[dependencies]
clap = "2.33.3"
console = "0.14.0"
serde_json = "1.0.61"
solana-account-decoder = "1.5.0"
solana-clap-utils = "1.5.0"
solana-cli-config = "1.5.2"
solana-cli-output = "1.5.0"
solana-client = "1.5.0"
solana-logger = "1.5.3"
solana-remote-wallet = "1.5.0"
solana-sdk = "1.5.0"
spl-token = { version = "3.0", path="../program", features = [ "no-entrypoint" ] }
spl-associated-token-account = { version = "1.0", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }

[[bin]]
name = "spl-token"
path = "src/main.rs"
