[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token Command-line Utility"
edition = "2021"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "spl-token-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "3.0.0"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = "2.33.3"
console = "0.15.7"
serde = "1.0.164"
serde_derive = "1.0.103"
serde_json = "1.0.99"
solana-account-decoder = "=1.16.1"
solana-clap-utils = "=1.16.1"
solana-cli-config = "=1.16.1"
solana-cli-output = "=1.16.1"
solana-client = "=1.16.1"
solana-logger = "=1.16.1"
solana-remote-wallet = "=1.16.1"
solana-sdk = "=1.16.1"
solana-transaction-status = "=1.16.1"
spl-token = { version = "4.0", path="../program", features = [ "no-entrypoint" ] }
spl-token-2022 = { version = "0.7", path="../program-2022", features = [ "no-entrypoint" ] }
spl-token-client = { version = "0.5", path="../client" }
spl-associated-token-account = { version = "2.0", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
spl-memo = { version = "4.0.0", path="../../memo/program", features = ["no-entrypoint"] }
strum = "0.25"
strum_macros = "0.25"
tokio = "1.14"

[dev-dependencies]
solana-test-validator = "=1.16.1"
assert_cmd = "2.0.5"
serial_test = "2.0.0"
tempfile = "3.6.0"

[[bin]]
name = "spl-token"
path = "src/main.rs"
