[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token Command-line Utility"
edition = "2018"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "spl-token-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "2.0.1"

[dependencies]
clap = "2.33.3"
console = "0.12.0"
serde_json = "1.0.57"
solana-account-decoder = { version = "1.3.12" }
solana-clap-utils = { version = "1.3.12"}
solana-cli-config = { version = "1.3.12" }
solana-client = { version = "1.3.11" }
solana-logger = { version = "1.3.12" }
solana-sdk = { version = "1.3.12" }
spl-token = { version = "2.0", path="../program" }

[[bin]]
name = "spl-token"
path = "src/main.rs"
