[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token Command-line Utility"
edition = "2021"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "spl-token-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "3.3.0"

[build-dependencies]
walkdir = "2"

[dependencies]
base64 = "0.21.5"
clap = "4.4.8"
console = "0.15.7"
futures = "0.3"
serde = "1.0.193"
serde_derive = "1.0.103"
serde_json = "1.0.108"
solana-account-decoder = "=1.17.6"
solana-clap-utils = "=1.17.6"
solana-cli-config = "=1.17.6"
solana-cli-output = "=1.17.6"
solana-client = "=1.17.6"
solana-logger = "=1.17.6"
solana-remote-wallet = "=1.17.6"
solana-sdk = "=1.17.6"
solana-transaction-status = "=1.17.6"
spl-token = { version = "4.0", path = "../program", features = [
  "no-entrypoint",
] }
spl-token-2022 = { version = "1.0", path = "../program-2022", features = [
  "no-entrypoint",
] }
spl-token-client = { version = "0.8", path = "../client" }
spl-token-metadata-interface = { version = "0.2", path = "../../token-metadata/interface" }
spl-associated-token-account = { version = "2.0", path = "../../associated-token-account/program", features = [
  "no-entrypoint",
] }
spl-memo = { version = "4.0.0", path = "../../memo/program", features = [
  "no-entrypoint",
] }
strum = "0.25"
strum_macros = "0.25"
tokio = "1.35"

[dev-dependencies]
solana-test-validator = "=1.17.6"
assert_cmd = "2.0.12"
libtest-mimic = "0.6"
serial_test = "2.0.0"
tempfile = "3.8.1"

[[bin]]
name = "spl-token"
path = "src/main.rs"

[[test]]
name = "command"
path = "tests/command.rs"
harness = false
