[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token Command-line Utility"
edition = "2018"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "spl-token-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "2.0.15"

[dependencies]
clap = "2.33.3"
console = "0.14.0"
indicatif = "0.16.2"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.68"
solana-account-decoder = "=1.9.5"
solana-clap-utils = "=1.9.5"
solana-cli-config = "=1.9.5"
solana-cli-output = "=1.9.5"
solana-client = "=1.9.5"
solana-logger = "=1.9.5"
solana-remote-wallet = "=1.9.5"
solana-sdk = "=1.9.5"
solana-transaction-status = "=1.9.5"
spl-token = { version = "3.3", path="../program", features = [ "no-entrypoint" ] }
spl-associated-token-account = { version = "1.0.5", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
spl-memo = { version = "3.0.1", path="../../memo/program", features = ["no-entrypoint"] }

[[bin]]
name = "spl-token"
path = "src/main.rs"
