[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token Command-line Utility"
edition = "2021"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "spl-token-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "2.4.0"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = "2.33.3"
console = "0.15.7"
serde = "1.0.164"
serde_derive = "1.0.103"
serde_json = "1.0.96"
solana-account-decoder = "=1.14.12"
solana-clap-utils = "=1.14.12"
solana-cli-config = "=1.14.12"
solana-cli-output = "=1.14.12"
solana-client = "=1.14.12"
solana-logger = "=1.14.12"
solana-remote-wallet = "=1.14.12"
solana-sdk = "=1.14.12"
solana-transaction-status = "=1.14.12"
spl-token = { version = "3.5", path="../program", features = [ "no-entrypoint" ] }
spl-token-2022 = { version = "0.6", path="../program-2022", features = [ "no-entrypoint" ] }
spl-token-client = { version = "0.5", path="../client" }
spl-associated-token-account = { version = "1.1", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
spl-memo = { version = "3.0.1", path="../../memo/program", features = ["no-entrypoint"] }
strum = "0.24"
strum_macros = "0.24"
tokio = "1.14"

[dev-dependencies]
solana-test-validator = "=1.14.12"
assert_cmd = "2.0.5"
serial_test = "2.0.0"
tempfile = "3.5.0"

[[bin]]
name = "spl-token"
path = "src/main.rs"
