[package]
name = "spl-slashing"
version = "0.1.0"
description = "Solana Program Library Slashing"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
bitflags = { version = "2.6.0", features = ["serde"] }
bytemuck = { version = "1.19.0", features = ["derive"] }
num_enum = "0.7.3"
generic-array = { version = "0.14.7", features = ["serde"], default-features = false }
bincode = "1.3.3"
num-derive = "0.4"
num-traits = "0.2"
solana-program = "2.1.0"
serde = "1.0.216" # must match the serde_derive version, see https://github.com/serde-rs/serde/issues/2584#issuecomment-1685252251
serde_bytes = "0.11.15"
serde_derive = "1.0.210" # must match the serde version, see https://github.com/serde-rs/serde/issues/2584#issuecomment-1685252251
serde_with = { version = "3.11.0", default-features = false }

thiserror = "2.0"
spl-pod = { version = "0.5.0", path = "../../libraries/pod" }

[dev-dependencies]
lazy_static = "1.5.0"
solana-program-test = "2.1.0"
solana-sdk = "2.1.0"
solana-ledger = "2.1.0"
solana-entry = "2.1.0"
solana-client = "2.1.0"
spl-record = { version = "0.3.0", path = "../../record/program" }
rand = "0.8.5"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
