[package]
name = "spl-tlv-account-resolution"
version = "0.7.0"
description = "Solana Program Library TLV Account Resolution Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
serde-traits = ["dep:serde"]
test-sbf = []

[dependencies]
bytemuck = { version = "1.17.0", features = ["derive"] }
serde = { version = "1.0.209", optional = true }
solana-program = "2.0.3"
spl-discriminator = { version = "0.3.0", path = "../discriminator" }
spl-program-error = { version = "0.5.0", path = "../program-error" }
spl-pod = { version = "0.3.0", path = "../pod" }
spl-type-length-value = { version = "0.5.0", path = "../type-length-value" }

[dev-dependencies]
futures = "0.3.30"
futures-util = "0.3"
solana-client = "2.0.3"
solana-program-test = "2.0.3"
solana-sdk = "2.0.3"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
