[package]
name = "spl-tlv-account-resolution"
version = "0.9.0"
description = "Solana Program Library TLV Account Resolution Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
serde-traits = ["dep:serde"]
test-sbf = []

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
serde = { version = "1.0.216", optional = true }
solana-account-info = "2.1.0"
solana-decode-error = "2.1.0"
solana-instruction = { version = "2.1.0", features = ["std"] }
solana-program-error = "2.1.0"
solana-msg = "2.1.0"
solana-pubkey = "2.1.0"
spl-discriminator = { version = "0.4.0", path = "../discriminator" }
spl-program-error = { version = "0.6.0", path = "../program-error" }
spl-pod = { version = "0.5.0", path = "../pod" }
spl-type-length-value = { version = "0.7.0", path = "../type-length-value" }
thiserror = "2.0"

[dev-dependencies]
futures = "0.3.31"
futures-util = "0.3"
solana-client = "2.1.0"
solana-program-test = "2.1.0"
solana-sdk = "2.1.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
