[package]
name = "spl-tlv-account-resolution"
version = "0.2.0"
description = "Solana Program Library TLV Account Resolution Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
test-sbf = []

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
solana-program = "1.16.1"
spl-discriminator = { version = "0.1", path = "../discriminator" }
spl-program-error = { version = "0.2.0", path = "../program-error" }
spl-type-length-value = { version = "0.2", path = "../type-length-value" }

[dev-dependencies]
solana-program-test = "1.16.1"
solana-sdk = "1.16.1"
spl-discriminator = { version = "0.1", path = "../discriminator" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
