[package]
name = "spl-tlv-account-resolution"
version = "0.5.0"
description = "Solana Program Library TLV Account Resolution Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
test-sbf = []

[dependencies]
bytemuck = { version = "1.14.0", features = ["derive"] }
solana-program = "1.17.6"
spl-discriminator = { version = "0.1", path = "../discriminator" }
spl-program-error = { version = "0.3", path = "../program-error" }
spl-type-length-value = { version = "0.3", path = "../type-length-value" }
spl-pod = { version = "0.1", path = "../pod" }

[dev-dependencies]
futures = "0.3.30"
futures-util = "0.3"
solana-client = "1.17.6"
solana-program-test = "1.17.6"
solana-sdk = "1.17.6"
spl-discriminator = { version = "0.1", path = "../discriminator" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
