[package]
name = "spl-tlv-account-resolution"
version = "0.1.0"
description = "Solana Program Library TLV Account Resolution Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
test-sbf = []

[dependencies]
bytemuck = { version = "1.13.0", features = ["derive"] }
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.6.1"
solana-program = "1.14.12"
spl-type-length-value = { version = "0.1", path = "../type-length-value" }
thiserror = "1.0"

[dev-dependencies]
solana-program-test = "1.14.12"
solana-sdk = "1.14.12"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
