[package]
name = "spl-managed-token"
version = "0.1.0"
description = "Solana Program Library Token Swap"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_managed_token"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
test = []

[dependencies]
borsh = "1.1"
shank = "^0.2.1"
solana-program = "1.17.2"
spl-associated-token-account = { version = "2.0", path = "../../associated-token-account/program", features = [ "no-entrypoint", ] }
spl-token = { version = "4.0", path = "../../token/program", features = ["no-entrypoint"] }
thiserror = "^1.0.50"

[dev-dependencies]
solana-program-test = "1.17.2"
solana-sdk = "1.17.2"
