[package]
name = "spl-identity"
version = "0.0.1"
description = "Solana Program Library Identity"
authors = ["dankelleher@yahoo.com"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
exclude_entrypoint = []

[dependencies]
borsh = "0.7.1"
num-derive = "0.3"
num-traits = "0.2"
remove_dir_all = "=0.5.0"
solana-program = "1.4.3"
thiserror = "1.0"
arrayref = "0.3.6"
num_enum = "0.5.1"

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]
