[package]
name = "spl-feature-proposal-cli"
version = "1.2.0"
description = "SPL Feature Proposal Command-line Utility"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = "2.33.3"
solana-clap-utils = ">=1.18.11,<=2"
solana-cli-config = ">=1.18.11,<=2"
solana-client = ">=1.18.11,<=2"
solana-logger = ">=1.18.11,<=2"
solana-sdk = ">=1.18.11,<=2"
spl-feature-proposal = { version = "1.0", path = "../program", features = ["no-entrypoint"] }

[[bin]]
name = "spl-feature-proposal"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
