[package]
name = "spl-elgamal-registry"
version = "0.1.0"
description = "Solana ElGamal Registry Program"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
solana-program = "2.1.0"
solana-zk-sdk = "2.1.0"
spl-pod = { version = "0.5.0", path = "../../../libraries/pod" }
spl-token-confidential-transfer-proof-extraction = { version = "0.2.0", path = "../proof-extraction" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
