[package]
name = "spl-discriminator"
version = "0.1.0"
description = "Solana Program Library 8-Byte Discriminator Management"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
borsh = ["dep:borsh"]

[dependencies]
borsh = { version = "0.10", optional = true }
bytemuck = { version = "1.13.1", features = ["derive"] }
solana-program = "1.16.1"
spl-discriminator-derive = { version = "0.1.0", path = "./derive" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
