[package]
name = "spl-record"
version = "0.2.1"
description = "Solana Program Library Record Program"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
bytemuck = { version = "1.17.1", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
solana-program = "2.0.3"
thiserror = "1.0"
spl-pod = { version = "0.4.0", path = "../../libraries/pod" }

[dev-dependencies]
solana-program-test = "2.0.3"
solana-sdk = "2.0.3"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
