
# Note: This crate must be built using do.sh

[package]
name = "spl-themis"
version = "0.1.0"
description = "Solana Program Library THEMIS"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
skip-no-mangle = ["solana-sdk/skip-no-mangle"]
program = ["solana-sdk/program"]
default = ["solana-sdk/default", "std", "u64_backend"]
std = ["curve25519-dalek/std"]
nightly = ["curve25519-dalek/nightly"]
u64_backend = ["curve25519-dalek/u64_backend"]

[dependencies]
bincode = "1.3"
borsh = "0.7.1"
curve25519-dalek = { version = "2", default-features = false, git = "https://github.com/garious/curve25519-dalek", rev = "60efef3553d6bf3d7f3b09b5f97acd54d72529ff" }
elgamal_ristretto = { git = "https://github.com/garious/elgamal", rev = "b0a2f5b2cbba052096aed56c26e3047c03fdbe70" }
getrandom = { version = "0.1.14", features = ["dummy"] }
num-derive = "0.3"
num-traits = "0.2"
rand = "0.7.0"
solana-sdk = { version = "1.3.12", default-features = false, optional = true }
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]

