[package]
name = "spl_shared_memory_client"
version = "0.0.1"
description = "SPL Shared-memory client"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[dev-dependencies]
rand = { version = "0.7.0"}
spl-shared-memory = { path = "../program" }
solana-bpf-loader-program = { version = "1.3.17" }
solana_rbpf = "=0.1.32"
solana-runtime = { version = "1.3.17" }
solana-sdk = { version = "1.3.17" }

