[package]
name = "heap-storage"
version = "0.1.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.1"
solana-program = "1.5.14"
thiserror = "1.0"
borsh = "0.8.2"

[dev-dependencies]
solana-program-test = "1.5.14"
solana-sdk = "1.5.14"
tokio = { version = "1.3.0", features = ["macros"]}

[lib]
crate-type = ["cdylib", "lib"]