[package]
name = "spl-program-metadata"
version = "0.0.1"
description = "Solana Program Metadata"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
solana-program = "1.6.2"
thiserror = "1.0"
borsh = "0.8.2"
spl-name-service = { path = "../../name-service/program", version = "0.1.0", features = [ "no-entrypoint" ] }

[lib]
crate-type = ["cdylib", "lib"]
