[package]
name = "spl-token-confidential-transfer-proof-extraction"
version = "0.1.0"
description = "Solana Program Library Confidential Transfer Proof Extraction"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = "1.19.0"
solana-curve25519 = "2.0.3"
solana-program = "2.0.3"
solana-zk-sdk = "2.0.3"
spl-pod = "0.4.0"
thiserror = "1.0.65"

[lib]
crate-type = ["cdylib", "lib"]
