[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token Command-line Utility"
edition = "2021"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "spl-transfer-hook-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.2.0"

[dependencies]
clap = { version = "4", features = ["cargo"] }
futures-util = "0.3.19"
solana-clap-v3-utils = "=1.17.6"
solana-cli-config = "=1.17.6"
solana-client = "=1.17.6"
solana-logger = "=1.17.6"
solana-remote-wallet = "=1.17.6"
solana-sdk = "=1.17.6"
spl-transfer-hook-interface = { version = "0.4", path = "../interface" }
spl-tlv-account-resolution = { version = "0.5" , path = "../../../libraries/tlv-account-resolution" }
strum = "0.25"
strum_macros = "0.25"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
solana-test-validator = "=1.17.6"
spl-token-2022 = { version = "1.0", path = "../../program-2022", features = ["no-entrypoint"] }
spl-token-client = { version = "0.8", path = "../../client" }

[[bin]]
name = "spl-transfer-hook"
path = "src/main.rs"
