[package]
name = "spl-pod"
version = "0.2.2"
description = "Solana Program Library Plain Old Data (Pod)"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
serde-traits = ["dep:serde", "dep:base64"]
borsh = ["dep:borsh"]

[dependencies]
base64 = { version = "0.22.1", optional = true }
borsh = { version = "1.5.1", optional = true }
bytemuck = { version = "1.16.0" }
serde = { version = "1.0.203", optional = true }
solana-program = ">=1.18.11,<=2"
solana-zk-token-sdk = ">=1.18.11,<=2"
spl-program-error = { version = "0.4.0", path = "../program-error" }

[dev-dependencies]
serde_json = "1.0.117"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
