[package]
name = "spl-pod"
version = "0.4.0"
description = "Solana Program Library Plain Old Data (Pod)"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
serde-traits = ["dep:serde"]
borsh = ["dep:borsh"]

[dependencies]
borsh = { version = "1.5.1", optional = true }
bytemuck = { version = "1.19.0" }
bytemuck_derive = { version = "1.8.0" }
serde = { version = "1.0.210", optional = true }
solana-program = "2.0.3"
solana-zk-sdk = "2.0.3"
spl-program-error = { version = "0.5.0", path = "../program-error" }

[dev-dependencies]
serde_json = "1.0.129"
base64 = { version = "0.22.1" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
