[package]
name = "spl-pod"
version = "0.1.0"
description = "Solana Program Library Plain Old Data (Pod)"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
serde-traits = ["dep:serde", "dep:base64"]
borsh = ["dep:borsh"]

[dependencies]
base64 = { version = "0.21.5", optional = true }
borsh = { version = "1.3", optional = true }
bytemuck = { version = "1.14.0" }
serde = { version = "1.0.193", optional = true }
solana-program = "1.17.6"
solana-zk-token-sdk = "1.17.6"
spl-program-error = { version = "0.3", path = "../program-error" }

[dev-dependencies]
serde_json = "1.0.108"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
