[package]
name = "spl-feature-proposal"
version = "1.0.0"
description = "Solana Program Library Feature Proposal Program"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
borsh = "1.1"
solana-program = "1.17.2"
spl-token = { version = "4.0", path = "../../token/program", features = ["no-entrypoint"] }

[dev-dependencies]
solana-program-test = "1.17.2"
solana-sdk = "1.17.2"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
