[package]
name = "spl-stake-pool"
version = "0.7.0"
description = "Solana Program Library Stake Pool"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.7"
borsh = "0.10"
bytemuck = "1.13"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.0"
serde = "1.0.188"
serde_derive = "1.0.103"
solana-program = "1.16.3"
spl-math = { version = "0.2", path = "../../libraries/math", features = [ "no-entrypoint" ] }
spl-pod = { version = "0.1", path = "../../libraries/pod", features = ["borsh"] }
spl-token-2022 = { version = "0.8", path = "../../token/program-2022", features = [ "no-entrypoint" ] }
thiserror = "1.0"
bincode = "1.3.1"

[dev-dependencies]
proptest = "1.2"
solana-program-test = "1.16.3"
solana-sdk = "1.16.3"
solana-vote-program = "1.16.3"
spl-token = { version = "4.0", path = "../../token/program", features = [ "no-entrypoint" ] }
test-case = "3.2"

[lib]
crate-type = ["cdylib", "lib"]
