[package]
name = "spl-stake-pool"
version = "2.0.1"
description = "Solana Program Library Stake Pool"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.9"
borsh = "1.5.3"
bytemuck = "1.20"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.3"
serde = "1.0.216"
serde_derive = "1.0.103"
solana-program = "2.1.0"
solana-security-txt = "1.1.1"
spl-pod = { version = "0.5.0", path = "../../libraries/pod", features = [
  "borsh",
] }
spl-token-2022 = { version = "6.0.0", path = "../../token/program-2022", features = [
  "no-entrypoint",
] }
thiserror = "2.0"
bincode = "1.3.1"

[dev-dependencies]
assert_matches = "1.5.0"
proptest = "1.5"
solana-program-test = "2.1.0"
solana-sdk = "2.1.0"
solana-vote-program = "2.1.0"
spl-token = { version = "7.0", path = "../../token/program", features = [
  "no-entrypoint",
] }
test-case = "3.3"

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true
