[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token Rust Client"
edition = "2021"
license = "Apache-2.0"
name = "spl-token-client"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.13.0"

[dependencies]
async-trait = "0.1"
bincode = "1.3.2"
bytemuck = "1.20.0"
futures = "0.3.31"
futures-util = "0.3"
solana-banks-interface = "2.1.0"
solana-cli-output = { version = "2.1.0", optional = true }
solana-program-test = "2.1.0"
solana-rpc-client = "2.1.0"
solana-rpc-client-api = "2.1.0"
solana-sdk = "2.1.0"
spl-associated-token-account-client = { version = "2.0.0", path = "../../associated-token-account/client" }
spl-elgamal-registry = { version = "0.1.0", path = "../confidential-transfer/elgamal-registry"}
spl-memo = { version = "6.0", features = ["no-entrypoint"] }
spl-record = { version = "0.3.0", path = "../../record/program", features = ["no-entrypoint"] }
spl-token = { version = "7.0", path = "../program", features = [
  "no-entrypoint",
] }
spl-token-confidential-transfer-proof-extraction = { version = "0.2.0", path = "../confidential-transfer/proof-extraction" }
spl-token-confidential-transfer-proof-generation = { version = "0.2.0", path = "../confidential-transfer/proof-generation" }
spl-token-2022 = { version = "6.0.0", path = "../program-2022" }
spl-token-group-interface = { version = "0.5.0", path = "../../token-group/interface" }
spl-token-metadata-interface = { version = "0.6.0", path = "../../token-metadata/interface" }
spl-transfer-hook-interface = { version = "0.9.0", path = "../transfer-hook/interface" }
thiserror = "2.0"

[features]
default = ["display"]
display = ["dep:solana-cli-output"]
