[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token Rust Client"
edition = "2021"
license = "Apache-2.0"
name = "spl-token-client"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.12.1"

[dependencies]
async-trait = "0.1"
bincode = "1.3.2"
bytemuck = "1.19.0"
futures = "0.3.31"
futures-util = "0.3"
solana-banks-interface = "2.0.3"
solana-cli-output = { version = "2.0.3", optional = true }
solana-program-test = "2.0.3"
solana-rpc-client = "2.0.3"
solana-rpc-client-api = "2.0.3"
solana-sdk = "2.0.3"
spl-associated-token-account-client = { version = "1.0.0", path = "../../associated-token-account/client" }
spl-memo = { version = "5.0", path = "../../memo/program", features = [
  "no-entrypoint",
] }
spl-record = { version = "0.2.1", path = "../../record/program", features = ["no-entrypoint"] }
spl-token = { version = "6.0", path = "../program", features = [
  "no-entrypoint",
] }
spl-token-confidential-transfer-proof-generation = { version = "0.1.0", path = "../confidential-transfer/proof-generation" }
spl-token-2022 = { version = "5.0.2", path = "../program-2022" }
spl-token-group-interface = { version = "0.4.2", path = "../../token-group/interface" }
spl-token-metadata-interface = { version = "0.5.1", path = "../../token-metadata/interface" }
spl-transfer-hook-interface = { version = "0.8.2", path = "../transfer-hook/interface" }
thiserror = "1.0"

[features]
default = ["display"]
display = ["dep:solana-cli-output"]
