[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token Rust Client"
edition = "2021"
license = "Apache-2.0"
name = "spl-token-client"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.5.0"

[dependencies]
async-trait = "0.1"
solana-cli-output = { version = "=1.14.12", optional = true }
solana-client = "=1.14.12"
solana-program-test = "=1.14.12"
solana-sdk = "=1.14.12"
# We never want the entrypoint for ATA, but we want the entrypoint for token when
# testing token
spl-associated-token-account = { version = "1.1", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
spl-memo = { version = "3.0.1", path = "../../memo/program", features = ["no-entrypoint"] }
spl-token = { version = "3.5", path="../program", features = [ "no-entrypoint" ] }
spl-token-2022 = { version = "0.6", path="../program-2022" }
spl-transfer-hook-interface = { version = "0.1", path="../transfer-hook-interface", features = [ "offchain-client" ] }
thiserror = "1.0"

[features]
default = ["display"]
display = ["dep:solana-cli-output"]
proof-program = ["spl-token-2022/proof-program"]
