[package]
name = "spl-metaplex"
version = "0.0.1"
description = "Metaplex"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
solana-program = "1.6.2"
spl-token = { path = "../../token/program", features = [ "no-entrypoint" ] }
spl-token-vault = { path = "../../token-vault/program", features = [ "no-entrypoint" ] }
spl-auction = { path = "../../auction/program", features = [ "no-entrypoint" ] }
thiserror = "1.0"
borsh = "0.8.2"

[lib]
crate-type = ["cdylib", "lib"]
