[package]
name = "spl-transfer-hook-interface"
version = "0.6.3"
description = "Solana Program Library Transfer Hook Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = "0.3.7"
bytemuck = { version = "1.15.0", features = ["derive"] }
solana-program = ">=1.18.2,<=2"
spl-discriminator = { version = "0.2.2" , path = "../../../libraries/discriminator" }
spl-program-error = { version = "0.4.0" , path = "../../../libraries/program-error" }
spl-tlv-account-resolution = { version = "0.6.3" , path = "../../../libraries/tlv-account-resolution" }
spl-type-length-value = { version = "0.4.3" , path = "../../../libraries/type-length-value" }
spl-pod = { version = "0.2.2", path = "../../../libraries/pod" }

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
tokio = { version = "1.36.0", features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
