[package]
name = "spl-hello-world-escrow"
version = "0.0.1"
description = "Solana Program Library Timelock"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-bpf = []
test-dump-genesis-accounts = []

[dependencies]
arrayref = "0.3.6"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "1.5.13"
spl-token = { path = "../../token/program", features = [ "no-entrypoint" ] }
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.4.0"
log = "0.4.8"
proptest = "0.10"
solana-program-test = "1.5.13"
solana-sdk = "1.5.13"
serde = "1.0"
serde_yaml = "0.8"
tokio = { version = "0.3", features = ["macros"]}

[lib]
crate-type = ["cdylib", "lib"]
