[package]
name = "spl_token_perf_monitor"
version = "0.0.1"
description = "SPL Token performance monitor"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[dev-dependencies]
rand = { version = "0.7.0"}
spl-token = { path = "../program", features = [ "exclude_entrypoint" ] }
solana-runtime = "1.4.4"
solana-sdk = "1.4.4"
solana-bpf-loader-program = "1.4.4"
solana_rbpf = "=0.1.32"
