[package]
name = "spl-concurrent-merkle-tree"
version = "0.2.0"
description = "Solana Program Library Concurrent Merkle Tree"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
log = []
sol-log = [ "log" ]

[dependencies]
solana-program = "1.16"
bytemuck = "1.14"
thiserror = "1.0.58"

[dev-dependencies]
rand_distr = "0.4.3"
rand = "0.8"
spl-merkle-tree-reference = { version = "0.1.0", path = "../merkle-tree-reference" }
tokio = { version = "1.36", features = ["full"] }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
