[package]
name = "spl-perpetual"
version = "0.1.0"
edition = "2018"
license = "WTFPL"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
solana-program = "1.6.2"
thiserror = "1.0.21"
spl-token = {version = "3.0.1", features = ["no-entrypoint"]}
arrayref = "0.3.6"
borsh = "0.8.2"
uint = "0.8"


[dev-dependencies]
assert_matches = "1.5.0"
base64 = "0.13"
log = "0.4.14"
proptest = "0.10"
solana-program-test = "1.6.2"
solana-sdk = "1.6.2"
serde = "1.0"
serde_yaml = "0.8"

[lib]
crate-type = ["cdylib", "lib"]
