[package]
name = "perpetual"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "1.6.2"
thiserror = "1.0.21"
spl-token = {version = "3.0.1", features = ["no-entrypoint"]}
arrayref = "0.3.6"
borsh = "0.8.2"

[lib]
crate-type = ["cdylib", "lib"]
