[package]
name = "spl-permissioned-transfer"
version = "0.1.0"
description = "Solana Program Library Permissioned Transfer"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
bytemuck = { version = "1.13.0", features = ["derive"] }
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.9"
solana-program = "1.14.12"
thiserror = "1.0"

[dev-dependencies]
solana-program-test = "1.14.12"
solana-sdk = "1.14.12"
spl-token = { version = "3.5",  path = "../program", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
