[package]
name = "spl-governance-tools"
version = "0.1.4"
description = "Solana Program Library Governance Tools"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = "0.3.7"
bincode = "1.3.2"
borsh = "1.5.1"
num-derive = "0.4"
num-traits = "0.2"
serde = "1.0.203"
serde_derive = "1.0.103"
solana-program = ">=1.18.11,<=2"
spl-token = { version = "4.0", path = "../../token/program", features = [
  "no-entrypoint",
] }
thiserror = "1.0"
