[package]
name = "spl-token-metadata-interface"
version = "0.1.0"
description = "Solana Program Library Token Metadata Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
borsh = "0.10"
solana-program = "1.16.1"
spl-discriminator = { version = "0.1.0" , path = "../../libraries/discriminator" }
spl-program-error = { version = "0.2.0" , path = "../../libraries/program-error" }
spl-type-length-value = { version = "0.2.0", features = ["borsh"], path = "../../libraries/type-length-value" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
