[package]
name = "spl-token-metadata-interface"
version = "0.4.0"
description = "Solana Program Library Token Metadata Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
serde-traits = ["dep:serde", "spl-pod/serde-traits"]

[dependencies]
borsh = "1.5.1"
serde = { version = "1.0.209", optional = true }
solana-program = "2.0.3"
spl-discriminator = { version = "0.3.0", path = "../../libraries/discriminator" }
spl-program-error = { version = "0.5.0", path = "../../libraries/program-error" }
spl-type-length-value = { version = "0.5.0", path = "../../libraries/type-length-value" }
spl-pod = { version = "0.3.0", path = "../../libraries/pod", features = [
  "borsh",
] }

[dev-dependencies]
serde_json = "1.0.125"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
