[package]
name = "spl-token-metadata-interface"
version = "0.1.0"
description = "Solana Program Library Token Metadata Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
serde-traits = ["serde"]

[dependencies]
borsh = "0.10"
solana-program = "1.16.3"
spl-discriminator = { version = "0.1.0" , path = "../../libraries/discriminator" }
spl-type-length-value = { version = "0.2.0", path = "../../libraries/type-length-value" }
serde = { version = "1.0.188", optional = true }
thiserror = "1.0.47"
num-traits = "0.2.16"
num-derive = "0.4.0"

[dev-dependencies]
serde_json = "1.0.105"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
