[package]
name = "spl-token-metadata-interface"
version = "0.2.0"
description = "Solana Program Library Token Metadata Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
serde-traits = ["dep:serde", "spl-pod/serde-traits"]

[dependencies]
borsh = "1.3"
serde = { version = "1.0.193", optional = true }
solana-program = "1.17.6"
spl-discriminator = { version = "0.1" , path = "../../libraries/discriminator" }
spl-program-error = { version = "0.3" , path = "../../libraries/program-error" }
spl-type-length-value = { version = "0.3", path = "../../libraries/type-length-value" }
spl-pod = { version = "0.1", path = "../../libraries/pod", features = ["borsh"] }

[dev-dependencies]
serde_json = "1.0.108"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
