name: Token Collection Pull Request

on:
  pull_request:
    paths:
    - 'token-collection/**'
    - 'token/**'
    - 'token-group/**'
    - 'token-metadata/**'
    - 'ci/*-version.sh'
    - '.github/workflows/pull-request-token-collection.yml'
    - '!token/js/**'
    - '!token-group/js/**'
    - '!token-metadata/js/**'
  push:
    branches: [master]
    paths:
    - 'token-collection/**'
    - 'token/**'
    - 'token-group/**'
    - 'token-metadata/**'
    - 'ci/*-version.sh'
    - '.github/workflows/pull-request-token-collection.yml'
    - '!token/js/**'
    - '!token-group/js/**'
    - '!token-metadata/js/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cargo-test-sbf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set env vars
        run: |
          source ci/rust-version.sh
          echo "RUST_STABLE=$rust_stable" >> $GITHUB_ENV
          source ci/solana-version.sh
          echo "SOLANA_VERSION=$solana_version" >> $GITHUB_ENV

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_STABLE }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUST_STABLE}}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/rustfilt
          key: cargo-sbf-bins-${{ runner.os }}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/solana
          key: solana-${{ env.SOLANA_VERSION }}

      - name: Install dependencies
        run: |
          ./ci/install-build-deps.sh
          ./ci/install-program-deps.sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Build and test
        run: ./ci/cargo-test-sbf.sh token-collection
