name: Docs Publish

on:
  push:
    branches:  [master]
    paths:
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "importing all the document"
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
        name: "installing the node.js with version 18"
      - name: "Build Docs"
        if: ${{ github.event_name == ('push' || 'pull_request')}} && ${{github.ref == 'master'}}
        run: |
         cd docs/
         npm ci
         ./build.sh
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
